In [2]:
import tensorflow as tf

# Create variable

In [3]:
my_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])
my_variable = tf.Variable(my_tensor)

# variables can be all kinds of types
bool_variable = tf.Variable([False, False, False, True])
complex_variable = tf.Variable([5+4j, 6+1j])

In [4]:
# variable has shape and dtype, can conver to numpy
print("shape: ", my_variable.shape)
print("dtype: ", my_variable.dtype)
print("as numpy", my_variable.numpy())

shape:  (2, 2)
dtype:  <dtype: 'float32'>
as numpy [[1. 2.]
 [3. 4.]]


In [5]:
# most tensor ops can be done on variables
print("as tensor: ", tf.convert_to_tensor(my_variable))
print("index of max: ", tf.argmax(my_variable))

# but cannot reshape variable, this will create a new tensor
print("copy and reshape: ", tf.reshape(my_variable, [1, 4]))

as tensor:  tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
index of max:  tf.Tensor([1 1], shape=(2,), dtype=int64)
copy and reshape:  tf.Tensor([[1. 2. 3. 4.]], shape=(1, 4), dtype=float32)


In [6]:
# can change the value of variable using assign
a = tf.Variable([2.0, 3.0])
a.assign([1, 2])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [7]:
a = tf.Variable([2.0, 3.0])
# this will duplicate a as a separate variable
b = tf.Variable(a)
a.assign([5, 6])

# a and b are now different
print(a.numpy())
print(b.numpy())

# can also assign with basic add and subtract
print(a.assign_add([2, 3]).numpy())
print(a.assign_sub([7, 9]).numpy())

[5. 6.]
[2. 3.]
[7. 9.]
[0. 0.]


In [8]:
# can set trainable to false
step_counter = tf.Variable(1, trainable=False)